"""Remove user_id from clients

Revision ID: 1020f8cd16e1
Revises: da95f378504f
Create Date: 2025-07-20 10:16:04.116284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1020f8cd16e1'
down_revision = 'da95f378504f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_clients_user_id', 'Users', ['user_id'], ['id'])

    # ### end Alembic commands ###
