"""Add business_user_id to WorkflowSetting table

Revision ID: 27ca409e87a8
Revises: 6bb831191480
Create Date: 2025-07-19 16:16:30.596826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ca409e87a8'
down_revision = '6bb831191480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_workflow_user', 'Users', ['business_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('business_user_id')

    # ### end Alembic commands ###
