"""Add manual_reset_time to User

Revision ID: 42bb89b5eae0
Revises: d2c993ce9ef6
Create Date: 2025-07-10 21:07:18.448624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42bb89b5eae0'
down_revision = 'd2c993ce9ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_reset_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('manual_reset_time')

    # ### end Alembic commands ###
