"""Add ClientReportAnalysis and ClientDisputeLetter tables

Revision ID: 469a68d7e384
Revises: 0c5302207815
Create Date: 2025-07-16 16:08:18.714489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469a68d7e384'
down_revision = '0c5302207815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_dispute_letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('letter_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('template_name', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_report_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('analysis_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_report_analysis')
    op.drop_table('client_dispute_letters')
    # ### end Alembic commands ###
