"""Add pdf, round_status & notes to clients

Revision ID: 6578139c95ab
Revises: 42bb89b5eae0
Create Date: 2025-07-15 12:47:09.997937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6578139c95ab'
down_revision = '42bb89b5eae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_filename', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('round_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('round_status')
        batch_op.drop_column('pdf_filename')

    # ### end Alembic commands ###
