"""Fix WorkflowSetting

Revision ID: 8f9908c88f5a
Revises: 27ca409e87a8
Create Date: 2025-07-19 18:36:50.101914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9908c88f5a'
down_revision = '27ca409e87a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_settings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_workflow_client_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_settings', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_workflow_client_key'), ['client_id', 'key'])

    # ### end Alembic commands ###
