"""Add DisputeRound model

Revision ID: d2c993ce9ef6
Revises: 5c37d0acb893
Create Date: 2025-07-10 14:11:02.032624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c993ce9ef6'
down_revision = '5c37d0acb893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispute_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pdf_hash', sa.String(length=64), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('disputed_accounts_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dispute_rounds')
    # ### end Alembic commands ###
