"""Add business_user_id to Client

Revision ID: da95f378504f
Revises: 8f9908c88f5a
Create Date: 2025-07-19 19:55:57.303699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da95f378504f'
down_revision = '8f9908c88f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_clients_business_user_id', 'Users', ['business_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('business_user_id')

    # ### end Alembic commands ###
